# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Executa sempre que houver push na branch principal
  push:
    branches: ["main"]

  # Executa toda sexta-feira às 10h (exemplo de agendamento)
  schedule:
    - cron: '0 10 * * FRI'

  # Permite executar manualmente a partir da aba Actions
  workflow_dispatch:

# Define as permissões necessárias
permissions:
  contents: read        # Necessário para fazer checkout do repositório
  pages: write          # Necessário para publicar no GitHub Pages
  id-token: write       # Necessário para usar o OIDC ao fazer o deploy

# Garantir que apenas um fluxo de deploy rode por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Clona o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Configura o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 3) Constrói o site Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      # 4) Envia a pasta _site como artefato, usando a versão v4 do upload
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 1) Baixa o artefato gerado no job anterior
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site

      # 2) Faz o deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
